In [1]:
! pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [7]:
a=[1,2,3,4,5,6]
arr = np.array(a)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(6,)


In [9]:
b=[[1,2],[3,4],[5,6]]
arr = np.array(b)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
2
(3, 2)


In [11]:
c=[[1,2],[3,4],[5,6],
   [4,5],[6,7]]
arr = np.array(c)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [4 5]
 [6 7]]
<class 'numpy.ndarray'>
2
(5, 2)


In [19]:
d= np.array([1,2,3,4,5,6,7,8,9,10])
print (d)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
print (d[0])
print (d[6])
print (d[5])

1
7
6


In [21]:
# Slicing
print (d[0:7])

[1 2 3 4 5 6 7]


In [22]:
# Stepping
print(d[2::2])

[3 5 7 9]


In [23]:
# Odd Numbers
print(d[::2])


[1 3 5 7 9]


In [27]:
# Even Numbers
print(d[1::2])

[ 2  4  6  8 10]
