In [ ]:
!pip install pillow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import PIL

In [ ]:
from PIL import Image

In [ ]:
img = Image.open('/content/poster.jpg')

In [ ]:
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1587x2245 at 0x7F53E4AF4390>


In [ ]:
print(img.size)

(1587, 2245)


In [ ]:
from numpy import asarray

In [ ]:
imgarr = asarray(img)

In [ ]:
print(imgarr)

[[[231 255 233]
  [231 255 233]
  [231 255 233]
  ...
  [ 62 109  55]
  [ 60 107  53]
  [ 58 105  51]]

 [[231 255 233]
  [231 255 233]
  [231 255 233]
  ...
  [113 155 107]
  [101 143  95]
  [ 87 129  81]]

 [[231 255 233]
  [231 255 233]
  [231 255 233]
  ...
  [222 255 218]
  [207 244 203]
  [189 226 185]]

 ...

 [[ 66 119  47]
  [ 62 115  43]
  [ 60 113  43]
  ...
  [ 11 137   1]
  [ 11 137   1]
  [ 11 137   1]]

 [[ 55 108  40]
  [ 54 109  41]
  [ 54 109  41]
  ...
  [ 10 136   0]
  [ 10 136   0]
  [ 10 136   0]]

 [[ 49 104  37]
  [ 53 108  41]
  [ 54 109  42]
  ...
  [ 10 136   0]
  [ 10 136   0]
  [ 10 136   0]]]
